Indenting status outputs

diff --git a/shared-shell-scripts/auto-start-remote-env b/shared-shell-scripts/auto-start-remote-env
--- a/shared-shell-scripts/auto-start-remote-env
+++ b/shared-shell-scripts/auto-start-remote-env
@@ -4,21 +4,21 @@ start-remote-env() {
     LAUNCH_SHELL=$1
     REMOTE_USER=$USER
     LOOPBACK_PORT=5555
-    echo "Launching remote environment for $ENVIRONMENT"
+    echo -e "    Launching remote environment for $ENVIRONMENT"
     while [ true ]; do
         ssh -R "$LOOPBACK_PORT":localhost:22 -o ExitOnForwardFailure=yes $2 -t "wget $SCRIPTFILE -O .setup_env.sh && ENVIRONMENT=$ENVIRONMENT bash .setup_env.sh $USER $LAUNCH_SHELL $LOOPBACK_PORT $ENVIRONMENT"
         EXIT_CODE=$?
         if [ $EXIT_CODE = 13 ]; then
             # We need to get the remote server's SSH key
-            echo "Need to install server's SSH key locally"
+            echo "    Need to install server's SSH key locally"
             echo "$(ssh -q $2 -t 'cat ~/.ssh/id_rsa.pub')" >> ~/.ssh/authorized_keys
         elif [ $EXIT_CODE = 0 ]; then
-            echo "Exiting normally"
+            echo "    Exiting normally"
             return 0
         elif [ $EXIT_CODE = 255 ]; then
             LOOPBACK_PORT=$(($LOOPBACK_PORT+1))
-            [ $LOOPBACK_PORT = 5565 ] && echo "ERROR: Ports 5555-5565 were all used. Exiting." && exit 1
-            echo "Exit code was $EXIT_CODE, trying port $LOOPBACK_PORT"
+            [ $LOOPBACK_PORT = 5565 ] && echo "    ERROR: Ports 5555-5565 were all used. Exiting." && exit 1
+            echo "    Exit code was $EXIT_CODE, trying port $LOOPBACK_PORT"
         fi
     done
 }
